---
title: "P8105 Final Project -- Proposal"
output: github_document
---

**Project Members**

* Amanda Nagle:           acn2138
* Amanda Kramer:          ark2187
* Jessica Flynn:          jf3200
* Sydney Ng:              sn2863
* Shannon Seonyoung Park: sp3804

**Tentative title:** Trends in US Border Crossings Over Time 

**Motivation:** Immigration has been a hotly contested issue during Trump’s presidency. Marking his words of building a “big, beautiful wall” in 2016, President Donald Trump got the green light from The Supreme Court in 2019 and $2.5 billion from the Pentagon’s budget to building up the U.S.-Mexico border. Although the data we found on border crossings on Kaggle are recorded, legal, and do not run into 2020, we were interested in looking at border crossing trends because of this issue. This analysis will help us understand and show how the border crossings play into life (e.g. movement of goods, commuting, holiday travel).

**Data Source:** https://www.kaggle.com/akhilv11/border-crossing-entry-data

**Intended final products:**

* An interactive leaflet heat map with location (latitude and longitude) of crossings of the US-Canada and US-Mexico borders.
* Graphics displaying trends regarding vehicle types crossing, months with heavy cross border traffic, and trends regarding holiday travel.
* A screencast with some slides as well as interactive visualization displays, as well as a website highlighting trends regarding border crossing between the US, Canada and Mexico.

**Things we are interested in analyzing and visualizing:**

* What is the distribution of recorded crossings between the US-Canada and US-Mexico borders?
* How busy are the busiest ports? Where are the busiest ports?
* Is there a time of the year when there are the most crossings? Are there holiday trends?
* What types of vehicles are crossing the borders the most? For a few ports (including Canadian ports)?
* Are there seasonal goods or commerce trends? (E.g., more private care cross US-Canada in the summer and maybe more truck crossings from Mexico in produce seasons.)

**Coding issues:** Some coding challenges we anticipating having are dealing with the latitudes and longitudes in the dataset and figuring out the interactive leaflet for the border crossings. It seems that we might have to separate the latitude and longitude coordinates because they are in one "location" column.

**Our timeline/plan:** We plan to perform exploratory data analysis the week following our Zoom project review meeting for firm up research questions we would like to explore, particularly from the questions we were initially interested in answering and any others that come up. Based on the questions we are interested, 2 weeks into the project we plan to do our analyses and create visualizations. In the week leading up to the December 5th due date, we will finalize our results and visualizations, write the report, and work on the screencast. We plan to meet at back together once a week and as needed, and to communicate pushes and pulls.
