---
title: "Border Crossings Interactive Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(shiny)
library(plotly)
library(leaflet)
```

```{r tidied_data, message=FALSE}
border_crossing_df = read_csv(file = "./Border_Crossing_Entry_Data.csv") %>% 
  janitor::clean_names() %>% 
  mutate(date = str_sub(date, end = -13), 
         location = str_replace(location, "POINT ", ""), 
         port_name_state = str_c(port_name, state, sep = "_")) %>% 
  separate(date, into = c("month", "day", "year"), sep = "/", convert = TRUE) %>% 
  select(-day, -port_name) %>% 
  separate(location, into = c("long", "lat"), sep = " ") %>% 
  mutate(long = str_replace(long, "\\(", ""), 
         lat = str_replace(lat, "\\)", ""), 
         long = as.numeric(long),
         lat =  as.numeric(lat)) %>% 
  filter(year >= 2000, year < 2019, value != 0)
```

Column {.sidebar}
-----------------------------------------------------------------------
```{r}
border_choices <- border_crossing_df %>%
  pull(border) %>%
  unique()

selectInput(
  inputId = "border_choice",
  label = h3("Border Choice"),
  choices = border_choices,
  selected = "US-Canada" # default
)

selectInput(
  inputId = "year_choice",
  label = h3("Year"),
  choices = c(2000:2018),
  selected = "2018" # default
)

# port_choices <- border_crossing_df %>%
#   pull(port_name_state) %>%
#   unique()
# 
# radioButtons( # not sure if we wanted to use this, but made it as a template
#   "port_choice",
#   h3("Port Choice"),
#   choices = port_choices
# )

```



Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
renderPlotly(
  border_crossing_df %>%
    mutate(text_label = str_c("Crossing type: ", 
                              measure, "\nNumber: ", value)) %>%
    filter(border == input[["border_choice"]],
           year == input[["year_choice"]]) %>%
    plot_ly(
      x = ~long, y = ~lat, 
      color = ~value, text = ~text_label,
      alpha = 0.5, type = "scatter", mode = "markers"
     )%>%
    add_markers(x = ~long, y = ~jitter(lat), 
                color = ~value,
                marker = list(size=6),
                hoverinfo = "text",
                text = ~paste0("Crossing type: ",
                              measure, "\nNumber: ", value),
                showlegend=TRUE)
)

```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart B

```{r}
pal <- colorNumeric(
  palette = "viridis",
  domain = border_crossing_df$value)

renderLeaflet(
  border_crossing_df %>%
  filter(border == input[["border_choice"]],
         year == input[["year_choice"]]) %>%
  leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addCircleMarkers(~long, ~jitter(lat), radius = .1, 
                   color = ~pal(value))
)
```

