---
title: "Border Crossings Report"
output: 
  html_document:
    toc: true
    toc_float: true
---

## Motivations

Immigration has been a hotly contested issue during Trump's presidency. Marking his words of building a "big, beautiful wall" in 2016, President Donald Trump got the green light from The Supreme Court in 2019 and $2.5 billion from the Pentagon's budget to building up the U.S.-Mexico border.

Ironically, despite the promise of his campaign to stop illegal immigration and build a strong bolder, the Trump administration faced a great challenge since the number of apprehensions significantly soar. For example, in August 2018, one-month total apprehensions was the highest on record and an 80 percent increase from July 2018. This trend is quite contrasting to the border crossing situation under the Obama administration. From 2008 to 2016, the yearly apprehensions on the Southwest border declined by 35 percent. 

Although the data we found on border crossings on Kaggle are recorded, legal, and do not run into 2020, we were interested in looking at border crossing trends because of this issue. Understanding the change in legal border crossing is crucial when considering the United States and Mexico's mutually dependent relationship in many aspects: including economy, separated immigrants' family issues, etc. Indeed, Mexico has remained the United States' second-largest export market since 1995, with exports totaling $242 billion in 2017.This analysis will help us understand and show how the border crossings play into life (e.g. movement of goods, commuting, holiday travel).

## Related Work
The following resources are a sample of what inspired this project.

* Trump wall: How much has he actually built?, BBC News, October 2020: [link](https://www.bbc.com/news/world-us-canada-46824649) 

## Initial Questions

* Are there any seasonal trends in border crossings? What are the general trends for vehicle compared to non-vehicle crossings, by month and year?

## Data

```{r include=FALSE}
library(tidyverse)
border_crossing_df = readRDS(file = "border_crossing_df_clean.rds")
```


### Source

Primary data source from Kaggle: [Border Crossing Entry Data](https://www.kaggle.com/akhilv11/border-crossing-entry-data) 

### Cleaning 

#### *Variables of Interest*

**Outcome**
`value`: A count of the number of crossings for each `measure` type at each `port_name_state` in each `month` of each `year`

**Predictors**

`state`: The state in which the border was located  
`port_code`: The code for the port in which the border entry took place  
`border`: Either the US-Canada or the US-Mexico border  
`month`: Month 1-12 in which the crossing took place  
`month_name`: Month name (Jan-Dec) in which the crossing took place  
`year`: Year from 2000 to 2018 in which the crossing took place  
`measure`: The type of vehicle or non-vehicle utilized in the border crossing. Potential entries include `r border_crossing_df %>% pull(measure) %>% unique()`  
`long`: Longitude of the port of the crossing
`lat`: Latitude of the port of the crossing
`port_name_state`: The port name and state for which the crossing took place. Some ports had the same name so this variable was created to append `state` as well.
`vehicle`: 

## Exploratory Data Analysis

#### _Crossings Monthly_

#### _Crossings Annually_

#### _Crossings of People_

#### _Crossings of Vehicles_

**Question: Are there any seasonal trends in border crossings? What are the general trends for vehicle compared to non-vehicle crossings, by month and year?**

Follow this link to [Crossings of Vehicles](crossings_vehicles.html).

Our graphs visualize both monthly and annual trends of border crossings for vehicles and non-vehicles, which we defined to be any passengers or pedestrians. We decided to explore the natural-log number of crossings due to a very right-skew of the data. This allowed us to examine the differences in trends for vehicle types, and to see that buses and personal vehicles have seasonality at the US-Canada border specifically in the summer months.

We also looked at the overall annual trends in border crossings by vehicles and non-vehicles and saw that they both ebb and flow similarly. This may be because the counts of passengers are correlated with the number of vehicles they correspond to, therefore the differences in the number of crossings is of less importance than the visual trend.

Finally, we further stratified our exploration of annual trends by border. We find that visually, there are consistently many more crossings at the US-Mexico border than at the US-Canada border. There is also a bigger gap between the vehicle and non-vehicle lines for the US-Mexico border, likely showing that there are more pedestrians and people per vehicle that for the US-Canada border. The lowest number of crossings at the US-Canada border is in 2009, whereas it is in 2011 at the US-Mexico border.


## Description of Approaches and Alternate Approaches

## Discussion

Lastly, in looking at the monthly and yearly trends of border crossings for vehicles and non-vehicles, we saw that the US-Mexico border has a larger volume of crossings and that there is some seasonality in US-Canada border crossings for personal vehicles and buses. We thought we would see seasonality at the US-Canada border during the summer months for summer vacation. We also expected to see a drop in border crossings overall during President Obama's first term around 2008-2012 due to nation-wide immigration issues. We also note that there is less seasonality in all other vehicles and at the US-Mexico border because commercial travel is not influenced by holiday/vacation seasons.

 