---
title: "Border Crossings Interactive Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(shiny)
library(plotly)
library(leaflet)
```

```{r tidied_data, message=FALSE}
month_df <- tibble(month = 1:12, month_name = month.name) %>%
         mutate(month_name = as.factor(month_name),
         month_name = fct_reorder(month_name, c("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December")))

border_crossing_df <- read_csv(file = "../Border_Crossing_Entry_Data.csv") %>% 
  janitor::clean_names() %>% 
  mutate(date = str_sub(date, end = -13), 
         location = str_replace(location, "POINT ", ""), 
         port_name_state = str_c(port_name, state, sep = "_")) %>% 
  separate(date, into = c("month", "day", "year"), sep = "/", convert = TRUE) %>%
  left_join(month_df, by = "month") %>%
  select(-day) %>% 
  separate(location, into = c("long", "lat"), sep = " ") %>% 
  mutate(long = str_replace(long, "\\(", ""), 
         lat = str_replace(lat, "\\)", ""), 
         long = as.numeric(long),
         lat =  as.numeric(lat)) %>% 
  filter(year >= 2000, year < 2019, value != 0)

# function to filter states
crossings_type_func <- function(choice, measure){
  if_else(choice %in% measure, TRUE, FALSE)
}

# function to exponential and round number of border crossings
round_exp <- function(val){
  exp(val) %>% round()
}
```

Column {.sidebar}
-----------------------------------------------------------------------
```{r sidebar_options}
# Border, drop down menu
border_choices <- border_crossing_df %>%
  pull(border) %>%
  unique()

selectInput(
  inputId = "border_choice",
  label = h3("Border Choice"),
  choices = border_choices,
  selected = "US-Canada" # default
)

# Year, drop down menu
selectInput(
  inputId = "year_choice",
  label = h3("Year"),
  choices = c(2000:2018),
  selected = "2018" # default
)

# Crossing types
crossing_choices <- border_crossing_df %>%
  pull(measure) %>%
  unique() %>%
  sort()

checkboxGroupInput(
  "crossings_choice",
  h3("Type of Crossing"),
  choices = crossing_choices,
  selected = crossing_choices # default is all crossing types
)

```



Column {data-width=500}
-----------------------------------------------------------------------

### Leaflet for Border Crossings

```{r crossings_leaflet}
pal <- colorNumeric(
  palette = "viridis",
  domain = log(border_crossing_df$value))

renderLeaflet(
  border_crossing_df %>%
    mutate(type_tf = map(measure, crossings_type_func,
                          input[["crossings_choice"]]),
           label_txt = str_c(month_name, ", ", year,
                             "<br>Port: ", port_name, ", ", state,
                             "<br>Type: ", measure,
                             "<br># of Crossings: ", value)) %>%
    filter(type_tf == TRUE,
           border == input[["border_choice"]],
           year == input[["year_choice"]]) %>%
    leaflet() %>% 
    addProviderTiles(providers$CartoDB.Positron) %>%
    addCircleMarkers(~jitter(long, factor = 10), 
                     ~jitter(lat, factor = 10), radius = 5, 
                     color = ~pal(log(value)), opacity = 0.25,
                     popup = ~label_txt) %>%
    addLegend("bottomright", pal = pal, values = ~log(value),
              title = "# of Crossings", opacity = 0.5, 
              labFormat = labelFormat(transform = round_exp)
              )
)

```

Column {data-width=450}
-----------------------------------------------------------------------

### Boxplot for Selected Crossings for Corresponding Border States

```{r}
renderPlotly({
    border_crossing_df %>%
    group_by(state, border, year, measure) %>%
    summarize(num = sum(value)) %>%
    filter(border == input[["border_choice"]],
           year == input[["year_choice"]]) %>%
    plot_ly(x = ~state, y = ~log(num), color = ~state, 
            type = "box", colors = "viridis", alpha = 0.5) %>%
    layout(xaxis = list(title = 'State'),
           yaxis = list(title = 'Ln Number of Crossings',
                        type = "log"))
})
```

### Monthly Trends for States for Selected Crossing Types

```{r}
renderPlotly({
    border_crossing_df %>%
    group_by(border, month_name, year, measure) %>%
    summarize(num = sum(value)) %>%
    mutate(type_tf = map(measure, crossings_type_func,
                          input[["crossings_choice"]])) %>%
    filter(type_tf == TRUE,
           border == input[["border_choice"]],
           year == input[["year_choice"]]) %>%
    plot_ly(x = ~month_name, y = ~log(num), color = ~measure, 
            type = "scatter", mode = "lines+markers",
            colors = "viridis", alpha = 0.5) %>%
    layout(xaxis = list(title = 'Month'),
           yaxis = list(title = 'Ln Number of Crossings',
                        type = "log"))
})

# border_crossing_df %>%
#     group_by(border, month, year, measure) %>%
#     summarize(num = sum(value)) %>%
#     filter(measure %in% c("Buses", "Pedestrians"),
#            border == "US-Canada Border",
#            year == 2018) %>%
#     plot_ly(x = ~as.factor(month), y = ~log(num), color = ~measure, 
#             type = "scatter", mode = "lines+markers",
#             colors = "viridis", alpha = 0.5) %>%
#     layout(xaxis = list(title = 'Month'),
#            yaxis = list(title = 'Ln Number of Crossings',
#                         type = "log"))
```

