---
title: "Report"
output: 
  html_document:
    toc: true
    toc_float: true
---

# Border Crossings Report

## Motivations

Immigration has been a hotly contested issue during Trump's presidency. Marking his words of building a "big, beautiful wall" in 2016, President Donald Trump got the green light from The Supreme Court in 2019 and $2.5 billion from the Pentagon's budget to building up the U.S.-Mexico border.

Ironically, despite the promise of his campaign to stop illegal immigration and build a strong bolder, the Trump administration faced a great challenge since the number of apprehensions significantly soar. For example, in August 2018, one-month total apprehensions was the highest on record and an 80 percent increase from July 2018. This trend is quite contrasting to the border crossing situation under the Obama administration. From 2008 to 2016, the yearly apprehensions on the Southwest border declined by 35 percent. 

Although the data we found on border crossings on Kaggle are recorded, legal, and do not run into 2020, we were interested in looking at border crossing trends because of this issue. Understanding the change in legal border crossing is crucial when considering the United States and Mexico's mutually dependent relationship in many aspects: including economy, separated immigrants' family issues, etc. Indeed, Mexico has remained the United States' second-largest export market since 1995, with exports totaling $242 billion in 2017.This analysis will help us understand and show how the border crossings play into life (e.g. movement of goods, commuting, holiday travel).

## Related Work

## Initial Questions

## Data Collection and Cleaning

## Exploratory Analysis

## Description of Approaches and Alternate Approaches

## Discussion


 